server:
  port: 8080

spring:
  application:
    name: smartroad-backend
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://smartroad_admin:smartroad_admin_23@cluster0.7vixs62.mongodb.net/smartroad_db?retryWrites=true&w=majority&appName=Cluster0}
  data:
    mongodb:
      database: smartroad_db
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://smartroad_admin:smartroad_admin_23@cluster0.7vixs62.mongodb.net/smartroad_db?retryWrites=true&w=majority&appName=Cluster0}
      auto-index-creation: false

smartroad:
  ai-service:
    base-url: http://localhost:8000
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000
